=head1 SMOKEPING

Documentation Overview

=over

=item L<INSTALL|Smokeping::INSTALL>

Installation Instructions

=item L<smokeping.pl smoke|Smokeping::Command::smoke>

run probing task

=item L<smokeping.cfg|Smokeping::Cfg>

Master configuration file.

=back

=head1 AUTHOR

L<Tobias Oetiker|http://tobi.oetiker.ch>, 2013-09-04

=cut

# Emacs Configuration
#
# Local Variables:
# mode: cperl
# eval: (cperl-set-style "PerlStyle")
# mode: flyspell
# mode: flyspell-prog
# End:
#
